# Generated by Django 2.2 on 2019-05-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'name']},
        ),
    ]
