# Generated by Django 2.2 on 2019-04-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='identifier',
            options={'verbose_name_plural': 'identifiers'},
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='entries', to='index.Author'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='entries', to='index.Category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='identifiers',
            field=models.ManyToManyField(blank=True, related_name='entries', through='index.Identifier', to='index.IdentifierType'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='index.Tag'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
