# Generated by Django 2.2 on 2019-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='keywords',
            field=models.TextField(blank=True, help_text='Space-separated keywords to improve text search. Normally not directly visible in the UI, but is returned in the API.'),
        ),
    ]
