# Generated by Django 2.2 on 2019-05-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_entry_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='keywords',
            field=models.TextField(blank=True, help_text='Space-separated keywords to improve text search. Normally not directly visible in the UI, but is returned in the API. Adding keywords that occur anywhere else (e.g. title, desc., URL, tags, categ., authors, sub entries) is redundant.'),
        ),
    ]
