# Generated by Django 2.2 on 2019-04-30 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190429_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='LengthUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'sub entries',
            },
        ),
        migrations.RenameModel(
            old_name='Identifier',
            new_name='EntryIdentifier',
        ),
        migrations.AlterModelOptions(
            name='entryidentifier',
            options={'verbose_name_plural': 'entry identifiers'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='length_seconds',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='length_words',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='parent',
        ),
        migrations.CreateModel(
            name='SubEntryIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.SubEntry')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.IdentifierType')),
            ],
            options={
                'verbose_name_plural': 'sub entry identifiers',
            },
        ),
        migrations.AddField(
            model_name='subentry',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='index.Entry'),
        ),
        migrations.AddField(
            model_name='subentry',
            name='identifier_types',
            field=models.ManyToManyField(blank=True, related_name='sub_entries', through='index.SubEntryIdentifier', to='index.IdentifierType'),
        ),
        migrations.AddField(
            model_name='subentry',
            name='length_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_entries', to='index.LengthUnit'),
        ),
        migrations.AddField(
            model_name='subentry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='index.SubEntry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='length_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='index.LengthUnit'),
        ),
    ]
