# Generated by Django 2.2 on 2019-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190514_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, help_text='Space-separated keywords to improve text search. Normally not directly visible in the UI, but is returned in the API. Adding keywords that occur in the title or parents is redundant.'),
        ),
    ]
