# Generated by Django 2.2 on 2019-04-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190430_0010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaType',
        ),
        migrations.RenameField(
            model_name='subentryidentifier',
            old_name='entry',
            new_name='sub_entry',
        ),
        migrations.AddField(
            model_name='lengthunit',
            name='name_plural',
            field=models.CharField(default='<plural name>', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lengthunit',
            name='name',
            field=models.CharField(help_text='Singular.', max_length=150),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
