# Generated by Django 2.2 on 2019-05-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_category_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
