# Generated by Django 2.2 on 2019-05-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190430_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['title'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='subentry',
            options={'ordering': ['title'], 'verbose_name_plural': 'sub entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, help_text='Supports Markdown.'),
        ),
        migrations.AlterField(
            model_name='subentry',
            name='description',
            field=models.TextField(blank=True, help_text='Supports Markdown.'),
        ),
    ]
