# Generated by Django 2.2 on 2019-05-02 14:02

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Category = apps.get_model('index', 'Category')
    for row in Category.objects.all():
        row.slug = uuid.uuid4()
        row.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_category_slug'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
